# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates
  schedule: [{cron: "0 */12 * * *"}]
  push: {branches: "main"}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # You'll need to setup a personal token in your secrets.
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: r-iskey
          template: classic
          config_order: languages, isocalendar, lines, stackoverflow
          base_indepth: yes
          plugin_lines: true
          plugin_lines_sections: repositories
          config_timezone: Asia/Yerevan
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_ignored: php
          plugin_languages_details: percentage
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 3049626
          plugin_stackoverflow_limit: 1
